project-tiki/project-tiki/Models/SingleProjectViewModel.cs
using project_tiki.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace project_tiki.Models
{
    public class SingleProjectViewModel
    {
        public SingleProjectViewModel(ViewProject theProject, List<AspNetUser> members, List<TaskList> taskLists)
        {
            this.TheProject = theProject;
            this.Members = members;
            this.TaskLists = taskLists;
        }

        public ViewProject TheProject { get; set; }
        public List<AspNetUser> Members { get; set; }
        public List<TaskList> TaskLists { get; set; }
    }
}

project-tiki/project-tiki/Controllers/SingleProjectController.cs
using project_tiki.Entities;
using Microsoft.AspNet.Identity;
using project_tiki.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using System.Globalization;

namespace project_tiki.Controllers
{
    public class SingleProjectController : Controller
    {
        private TikiEntities db = new TikiEntities();
        // GET: SingleProject
        public ActionResult Index(int? id)
        {

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Project proj = db.Projects.Find(id);
            if (proj == null)
            {
                return HttpNotFound();
            }
            if (!userHasAccess((int)id))
            {
                //throw new UnauthorizedAccessException("Sorry, you do not have access to that team | We'll probably want to redirect them maybe?");
                return RedirectToAction("Index", "UserLanding");
            }

            int curTeamID = db.TeamProjects.Where(tp => tp.ProjectId == proj.Id).FirstOrDefault().TeamId;
            //gets all teamMembers on that team
            List<TeamMember> teamMembers = db.TeamMembers.Where(tm => tm.TeamId == curTeamID).ToList();
            List<AspNetUser> theMembers = new List<AspNetUser>();
            foreach (TeamMember tm in teamMembers)
            {
                var memID = tm.MemberId;
                //adds all AspNetUser counterparts to teamMembers
                theMembers.AddRange(db.AspNetUsers.Where(p => p.Id.Equals(memID)));
            }
            DateTime lastEdited = proj.Date_Created;
            String tempStoredID = "P" + proj.Id;
            var lastEdit = db.Logs.Where(l => l.StoredId.Equals(tempStoredID)).ToList();
            for (int j = 0; j < lastEdit.Count; j++)
            {
                if (j == lastEdit.Count - 1)
                {
                    lastEdited = lastEdit.ElementAt(j).Date_Edited;
                }
            }
            ViewProject tempViewProject = new ViewProject(proj, theMembers, lastEdited);
            List<TaskList> projectTasks = new List<TaskList>();

            List<ProjectNote> pns = db.ProjectNotes.Where(pn => pn.ProjectId == proj.Id).ToList();

            Dictionary<Tag, List<SingleTask>> TagToList = new Dictionary<Tag, List<SingleTask>>();

            foreach (ProjectNote pn in pns)
            {
                Note tempNote = pn.Note;
                SingleTask tempTask = new SingleTask(theMembers, tempNote, lastEdited);
                String tempStore = "N" + tempNote.Id;
                List<NoteTag> tags = db.NoteTags.Where(nt => nt.StoredId.Equals(tempStore)).ToList();
                foreach (NoteTag nt in tags)
                {
                    Tag tempTag = nt.Tag;
                    if (TagToList.ContainsKey(tempTag))
                    {
                        List<SingleTask> oldTasks;
                        var test = TagToList.TryGetValue(tempTag, out oldTasks);
                        oldTasks.Add(tempTask);
                        TagToList.Remove(tempTag);
                        TagToList.Add(tempTag, oldTasks);
                    }
                    else
                    {
                        List<SingleTask> theTasks = new List<SingleTask>();
                        theTasks.Add(tempTask);
                        TagToList.Add(tempTag, theTasks);
                    }
                }

            }
            var count = 0;
            foreach (KeyValuePair<Tag, List<SingleTask>> lst in TagToList)
            {
                TaskList tempPls = new TaskList(lst.Value, count, lst.Key.Title);
                count++;
                projectTasks.Add(tempPls);
            }


            SingleProjectViewModel plsWork = new SingleProjectViewModel(tempViewProject, theMembers, projectTasks);

            return View(plsWork);
        }
        public Boolean userHasAccess(int requestedID)
        {
            var signedInUserIdentity = User.Identity.GetUserId();
            List<int> teamIDs = new List<int>();
            var allTeamMembers = db.TeamMembers.Where(tm => tm.MemberId.Equals(signedInUserIdentity)).ToList();
            for (int i = 0; i < allTeamMembers.Count; i++)
            {
                int curID = allTeamMembers[i].TeamId;
                teamIDs.Add(curID);
            }
            //will not have gotten here unless project exists
            Project proj = db.Projects.Find(requestedID);

            List<TeamProject> tps = new List<TeamProject>();
            foreach (int i in teamIDs)
            {
                List<TeamProject> tempTPs = db.TeamProjects.Where(tp => tp.ProjectId == proj.Id).ToList();
                tps.AddRange(tempTPs);
            }
            Boolean userHasAccess = false;

            foreach (TeamProject tp in tps)
            {
                foreach (int i in teamIDs)
                {
                    if (tp.TeamId == i)
                    {
                        userHasAccess = true;
                    }
                }
            }

            return userHasAccess;
        }

        //called when a user wants to change members
        public PartialViewResult ChangeMembers(int projid)
        {
            List<TeamProject> tempPeople = db.TeamProjects.Where(tp => tp.ProjectId == projid).ToList();
            List<AspNetUser> people = new List<AspNetUser>();
            foreach (TeamProject tp in tempPeople)
            {
                foreach (TeamMember t in tp.Team.TeamMembers)
                {
                    people.Add(db.AspNetUsers.Where(p => p.Id.Equals(t.MemberId)).FirstOrDefault());
                }
            }

            ViewBag.Members = people.Distinct();

            return PartialView("OpenEditMembers");
        }

        //called when they change members
        public ActionResult MemberDeleted(int memberid, int noteid)
        {
            //should prob assign them back to the model

            //will reload the note page to update the members, ignore the 0, it was for not getting yelled at
            return Index(0);
        }

        //called when a user clicks the button to change theme stuff
        public PartialViewResult ChangeTheme(int projid)
        {
            Project temp = db.Projects.Where(p => p.Id == projid).Single();
            ViewBag.theProject = temp;
            return PartialView("OpenEditTheme");
        }

        //called when a user edits theme preferences
        [HttpPost]
        public ActionResult ThemeEdited()
        {
            //gets the theme stuff
            string bgColor = Request["bgColor"];
            string fontcolor = Request["color"];
            string font = Request["font"];
            int projid = Convert.ToInt32(Request["projid"].ToString());
            //should prob reassign that stuff

            foreach (Project p in db.Projects.Where(p => p.Id == projid))
            {
                p.Background_Color = bgColor;
                p.Font_Color = fontcolor;
                p.Font_Url = font;
            }

            db.SaveChanges();

            //updates the note view to have the new stuff
            return Index(projid);
        }


        [HttpPost]
        public IEnumerable<AspNetUser> UserSearched()
        {
            //gets the username the user is looking for
            string searched = Request["username"];

            //pls return me the list of users that contain the string in their username

            List<AspNetUser> returnedUsers = db.AspNetUsers.Where(p => p.UserName.ToLower().Contains(searched.ToLower())).ToList();

            return returnedUsers;
        }

        //Opens the pop up to edit members
        public ActionResult OpenEditMembers(IEnumerable<AspNetUser> members)
        {
            ViewBag.Members = members;
            return View();
        }

        //opend the pop up to edit theme stuff
        public ActionResult OpenEditTheme(SingleTask task)
        {
            return View(task);
        }

        public PartialViewResult ViewTask(SingleTask task)
        {
            return PartialView(task);
        }

        [HttpPost]
        public ActionResult TaskEdited()
        {
            string title = Request["title"];
            string content = Request["content"];
            int taskid = Convert.ToInt32(Request["taskid"].ToString());
            string backgroundColor = Request["bgColor"];
            string color = Request["color"];
            string font = Request["font"];
            var members = Request["members"];

            //can make whatever out of that

            return null;
        }

        public ActionResult Archive(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Project project = db.Projects.Find(id);
            if (project == null)
            {
                return HttpNotFound();
            }
            //Archive and Log Notes Related to the Project
            List<ProjectNote> projectNotes = db.ProjectNotes.Where(pn => pn.ProjectId == project.Id).ToList();
            List<Note> notes = db.Notes.ToList();
            foreach (Note note in notes)
            {
                foreach (ProjectNote projectNote in projectNotes)
                {
                    if (note.Id.Equals(projectNote.NoteId))
                    {
                        NoteArchive noteArchive = new NoteArchive { Title = note.Title, Content = note.Content, Date_Created = note.Date_Created, Date_Due = DateTime.Now.AddDays(30) };
                        db.NoteArchives.Add(noteArchive);
                        Log log = new Log { Date_Edited = DateTime.Now, Editor = User.Identity.GetUserId(), StoredId = "Z" + noteArchive.Id, Details = note.Id + " was and is now Z" + noteArchive.Id };

project-tiki/project-tiki/Views/SingleProject/Create.cshtml
﻿@model project_tiki.Models.NoteViewEditViewModel
@Styles.Render("~/public/css/editnote.css")
@Styles.Render("~/public/css/cproject.css")

<h2 class="text-center">Create a Project</h2>

<div class="text-center">
          @using (Html.BeginForm())
          {
                    
                    @Html.TextBox("title", "", new { placeholder = "Project Title" })
                    <br />
                    <label for="datedue">Enter a due date for this project:</label>
                    <br />
                    @Html.TextBox("datedue", "", new { placeholder = "mm/dd/yyyy" })
                    <br />
                    <input type="submit" value="Create Project" />
          }
</div>

project-tiki/project-tiki/Views/SingleProject/Index.cshtml
@model project_tiki.Models.SingleProjectViewModel
@Styles.Render("~/public/css/project.css")

@{ 
    ViewBag.changeID = "/SingleProject/ChangeMembers/" + Model.TheProject.ProjectID;
    ViewBag.themeID = "/SingleProject/ChangeTheme/" + Model.TheProject.ProjectID;

}


<div id="ProjectHead">
    <h2>@Model.TheProject.Title</h2>


    
    <a href=@ViewBag.changeID>Change Members</a> | 
    <a href=@ViewBag.themeID>Change Theme</a>
    </div>

<div class="row">
    @foreach (var list in Model.TaskLists)
    {
    @Html.Partial("TaskListPartial", list)
    }
</div>

project-tiki/project-tiki/Views/SingleProject/OpenEditMembers.cshtml
@model project_tiki.Models.ViewNote

@Styles.Render("~/public/css/editnote.css")
@Styles.Render("~/public/css/editmembers.css")

                <h2 class="modal-title">Edit Members</h2>
            
                @foreach (var member in ViewBag.Members)
                {
                    <div class="memberButtons">
                        <label>@member.UserName</label>
                        <button type="button" class="btn btn-danger">
                             <span class="glyphicon glyphicon-remove"></span>
                        </button>
                        </div>
                }
           
               <h3>Add a Member</h3>
                @using (Html.BeginForm("UserSearched", "SingleProject"))
                {
                    <label>User Name:</label>
                    @Html.TextBox("username")
                    <input type="submit" value="Search" />
                }

project-tiki/project-tiki/Views/SingleProject/OpenEditTheme.cshtml
@model project_tiki.Models.SingleProjectViewModel
@Styles.Render("~/public/css/editnote.css")
@Styles.Render("~/public/css/edittheme.css")

<h2 class="modal-title">Edit Theme</h2>
@using (Html.BeginForm("ChangeTheme", "SingleProject"))
            {
    <h4>Project Color</h4>
                <div class="colors btn-group" data-toggle="buttons">
                    <label style="background-color: #FFFFFF;" class="colors btn btn-default">
                        <input type="radio" value="0"  />
                    </label>
                    <label style="background-color: #DDF9D9;" class="colors btn btn-default">
                        <input id="ctwo" type="radio" value="0"  />
                    </label>
                    <label style="background-color: #529A86;" class="colors btn btn-default">
                        <input id="cthree" type="radio" value="0"  />
                    </label>
                    <label style=" background-color #D1FAFF;" class="colors btn btn-default">
                        <input id="cfour" type="radio" value="0"  />
                    </label>
                </div>

                    <h4>Project Font</h4>
                    <div class="btn-group" data-toggle="buttons">
                        <label class="btn btn-default">
                            <input type="radio"  /> Arial
                        </label>
                        <label class="btn btn-default">
                            <input id="ftwo" type="radio"  /> Montserrat
                        </label>
                        <label class="btn btn-default">
                            <input id="fthree" type="radio" /> Times
                        </label>
                        <label class="btn btn-default">
                            <input id="ffour" type="radio"  /> Roboto
                        </label>
                    </div>

                    <h4>Project Font Color</h4>
                    <div class="btn-group" data-toggle="buttons">
                        <label class="btn btn-default">
                            <input type="radio" value="0" /> White
                        </label>
                        <label style="color: #000000;" class="btn btn-default">
                            <input type="radio" value="0" /> Black
                        </label>
                        <label style="color: #E8432B;" class="btn btn-default">
                            <input type="radio" value="0"/> Red
                        </label>
                        <label style="color: #ACEBAE;" class="btn btn-default">
                            <input type="radio" value="0" /> Mint
                        </label>
                    </div>
                    <br />
                    <br />
                    <input type="submit" value="Save Changes" />
}

project-tiki/project-tiki/Views/SingleProject/RedirectPls.cshtml
﻿@model project_tiki.Models.NoteViewEditViewModel
@Styles.Render("~/public/css/editnote.css")
@Styles.Render("~/public/css/cproject.css")

<div class="text-center">
    <h1>@ViewBag.Message</h1>
</div>

project-tiki/project-tiki/Views/SingleProject/ViewTask.cshtml
@model project_tiki.Models.ViewNote
@Styles.Render("~/public/css/main.css")
@Styles.Render("~/public/css/editnote.css")

@{
    ViewBag.Members = "";

    foreach (var m in Model.Members)
    {
        ViewBag.Members += m.UserName + " ";
    }
}

<div class="row">
    <div style="font-face{font-family: 'TheFont'; src: url(@Model.FontSource);} background-color: @Model.Background; color: @Model.Color; font-family: 'TheFont';">
        @using (Html.BeginForm("TaskEdited", "SingleProject"))
        {
            @Html.TextBox("title", Model.Title, new { maxlength = 20, placeholder = "Task Title" })
            <div id="note">
                @Html.TextArea("content", Model.Content, new { placeholder = "Write your task description here" })
                </div>
            <p>Last Edited: @Model.LastEdited</p>
            <input type="submit" value="Save" />
            <div style="display: none; visibility: hidden;">
                @Html.TextBox("taskid", Model.NoteID)
                @Html.TextBox("bgColor", Model.Background)
                @Html.TextBox("color", Model.Color)
                @Html.TextBox("font", Model.FontSource)
                @Html.TextBox("members", Model.Members)
            </div>
        }
    </div>
</div>