project-tiki/project-tiki/Models/NoteViewEditViewModel.cs
using project_tiki.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace project_tiki.Models
{
    public class NoteViewEditViewModel
    {
        public NoteViewEditViewModel(ViewNote theNote, List<AspNetUser> members)
        {
            this.TheNote = theNote;
            this.Members = members;
        }
        public ViewNote TheNote { get; set; }
        public List<AspNetUser> Members { get; set; }
    }
}

project-tiki/project-tiki/Controllers/NoteViewEditController.cs
using project_tiki.Entities;
using Microsoft.AspNet.Identity;
using project_tiki.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace project_tiki.Controllers
{
    public class NoteViewEditController : Controller
    {
        private TikiEntities db = new TikiEntities();
        // GET: NoteViewEdit
        public ActionResult Index(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Note note = db.Notes.Find(id);
            if (note == null)
            {
                return HttpNotFound();
            }
            if (!userHasAccess((int)id))
            {
                return RedirectToAction("Index", "UserLanding");
            }

            //~~~~~~~~~~~~~~~
            
           
            //gets the first instance of note where ids match because the IDs should be unique
            Note theNote = db.Notes.Where(no => no.Id == (int)id).FirstOrDefault();
            //gets the teamID from the note
            int curTeamID = db.TeamNotes.Where(tn => tn.NoteId == (int)id).FirstOrDefault().TeamId;
            //gets all teamMembers on that team
            List<TeamMember> teamMembers = db.TeamMembers.Where(tm => tm.TeamId == curTeamID).ToList();
            List<AspNetUser> theMembers = new List<AspNetUser>();
            foreach (TeamMember tm in teamMembers)
            {
                var memID = tm.MemberId;
                //adds all AspNetUser counterparts to teamMembers
                theMembers.AddRange(db.AspNetUsers.Where(p => p.Id.Equals(memID)));
            }
            //gets the last time the note was put into the log table
            String tempStoredID = "N" + (int)id;
            var lastEdit = db.Logs.Where(l => l.StoredId.Equals(tempStoredID)).ToList();
            Note actualNote = db.Notes.Where(no => no.Id == (int)id).FirstOrDefault();
            DateTime lastEdited = actualNote.Date_Created;
            for (int j = 0; j < lastEdit.Count; j++)
            {
                if (j == lastEdit.Count - 1)
                {
                    lastEdited = lastEdit.ElementAt(j).Date_Edited;
                }
            }
            //gets all noteTags tied to current note
            List<NoteTag> noteTags = db.NoteTags.Where(no => no.StoredId.Equals(tempStoredID)).ToList();
            List<Tag> tags = new List<Tag>();
            foreach (NoteTag nt in noteTags)
            {
                //gets all tags corresponding to the tagIDs
                tags.AddRange(db.Tags.Where(t => t.Id == nt.TagId).ToList());
            }

            ViewNote tempNote2 = new ViewNote(theNote, theMembers, lastEdited, tags);


            NoteViewEditViewModel tempModel = new NoteViewEditViewModel(tempNote2, theMembers);
            return View(tempModel);
        }
    public Boolean userHasAccess(int requestedID)
        {
            var signedInUserIdentity = User.Identity.GetUserId();
            List<int> teamIDs = new List<int>();
            var allTeamMembers = db.TeamMembers.Where(tm => tm.MemberId.Equals(signedInUserIdentity)).ToList();
            for (int i = 0; i < allTeamMembers.Count; i++)
            {
                int curID = allTeamMembers[i].TeamId;
                teamIDs.Add(curID);
            }
            //will not have gotten here unless project exists
            Note note = db.Notes.Find(requestedID);
            List<TeamNote> allTNs = new List<TeamNote>();
            foreach(int t in teamIDs)
            {
                List<TeamNote> tns = db.TeamNotes.Where(tn => tn.TeamId == t).ToList();
                allTNs.AddRange(tns);
            }
            Boolean userHasAccess = false;

            foreach (TeamNote tn in allTNs)
            {
                foreach (int i in teamIDs)
                {
                    if (tn.TeamId == i)
                    {
                        userHasAccess = true;
                    }
                }
            }

            return userHasAccess;
        }

 //called when a user wants to change members
        public ViewResult ChangeMembers(int noteid)
        {
            int actualID = noteid;
            ViewBag.NoteID = actualID;
            List<AspNetUser> tempMembers = new List<AspNetUser>();
            List <TeamNote> teamNotes = db.TeamNotes.Where(tn => tn.NoteId == actualID).ToList();
            foreach(TeamNote tn in teamNotes)
            {
                List<TeamMember> tempTMs = db.TeamMembers.Where(tm => tm.TeamId == tn.TeamId).ToList();
                foreach(TeamMember tm in tempTMs)
                {
                    tempMembers.AddRange(db.AspNetUsers.Where(p => p.Id.Equals(tm.MemberId)).ToList());
                }
            }
            ViewBag.Members = tempMembers.Distinct();
            return View("OpenEditMembers");
        }

        //called when they change members
        public ActionResult MemberDeleted(int memberid, int noteid)
        {
            //should prob assign them back to the model

            //will reload the note page to update the members, ignore the 0, it was for not getting yelled at
            return Index(0);
        }

        //called when a user clicks the button to change theme stuff
        //public ViewResult ChangeTheme(int noteid) {
        //    ViewBag.theNote = db.Notes.Where(n => n.Id == noteid).FirstOrDefault();
        //    return View("OpenEditTheme");
        //}

        //called when a user edits theme preferences
        [HttpPost]
        public ActionResult ChangeTheme(){
            //gets the theme stuff
            var idefk = Request.Form;
            string bgColor = Request["bgColor"];
            string fontcolor = Request["color"];
            string font = Request["font"];
            int noteid = Convert.ToInt32(Request["noteid"].ToString());
            //should prob reassign that stuff

            foreach(Note n in db.Notes.Where(n => n.Id == noteid))
            {
                n.Background_Color = bgColor;
                n.Font_Color = fontcolor;
                n.Font_Url = font;
            }

            db.SaveChanges();

            //updates the note view to have the new stuff
            return RedirectToAction("Index", "UserLanding", null);
        }

        //gets the form information from the note view edit view
        [HttpPost]
        public ActionResult Edited()
        {
            
            string title = Request["title"];
            string content = Request["content"];
            string tags = Request["tags"];
            int noteid = Convert.ToInt32(Request["noteid"].ToString());
            string backgroundColor = Request["bgColor"];
            string color = Request["color"];
            string font = Request["font"];
            var members = Request["members"];
            Note tempNote = db.Notes.Where(no => no.Id == noteid).FirstOrDefault();
            Note n = new Note
            {
                Background_Color = backgroundColor,
                Content = content,
                Date_Created = tempNote.Date_Created,
                Font_Color = color,
                Font_Url = font,
                Title = title,
                Id = tempNote.Id,
                Date_Due = tempNote.Date_Due,
                ProjectNotes = tempNote.ProjectNotes,
                TeamNotes = tempNote.TeamNotes
            };

            List<String> tempTags = tags.Split(',').ToList();
            String storeID = "N" + noteid;
            foreach(String s in tempTags)
            {
                String tempStr = s.Trim(' ');
                
                List<Tag> posTag = db.Tags.Where(t => t.Title.ToLower().Equals(tempStr.ToLower())).ToList();
                if (posTag.Count > 0)
                {
                    List<NoteTag> nts = db.NoteTags.Where(nt => nt.StoredId.Equals(storeID)).ToList();
                    Boolean matchFound = false;
                    foreach(NoteTag nt in nts)
                    {
                        if(nt.TagId == posTag.First().Id)
                        {
                            matchFound = true;
                        }
                    }
                    if (!matchFound)
                    {
                        db.NoteTags.Add(new NoteTag { StoredId = storeID, TagId = posTag.First().Id });
                        db.SaveChanges();
                    }
                }else
                {
                    int tempTagIDOLD = db.Tags.OrderByDescending(t => t.Id).First().Id;
                    Tag theTempTag = new Tag { Title = tempStr , Id = (tempTagIDOLD + 1) };
                    db.Tags.Add(theTempTag);
                    db.SaveChanges();
                    int tempTagID = db.Tags.OrderByDescending(t => t.Id).First().Id;
                    db.NoteTags.Add(new NoteTag { StoredId = storeID, TagId = tempTagID });
                    db.SaveChanges();
                }
            }

            //REMOVE THE TAGS THAT AREN'T THERE

            List<NoteTag> allTheNoteTags = db.NoteTags.Where(nt => nt.StoredId == storeID).ToList();
            foreach(NoteTag nt in allTheNoteTags)
            {
                Tag curTag = nt.Tag;
                Boolean tagIsFound = false;
                foreach(String s in tempTags)
                {
                    if (s.Trim().ToLower().Equals(curTag.Title.Trim().ToLower()))
                    {
                        tagIsFound = true;
                    }
                }
                if (!tagIsFound)
                {
                    db.NoteTags.Remove(nt);
                    db.SaveChanges();
                }
            }







            foreach(Note tempNotePls in db.Notes.Where(no => no.Id == noteid))
            {
                tempNotePls.Background_Color = n.Background_Color;

project-tiki/project-tiki/Views/NoteViewEdit/Create.cshtml
@model project_tiki.Models.NoteViewEditViewModel
@Styles.Render("~/public/css/editnote.css")

<h2>Create a Note</h2>

<div class="row">
          @using (Html.BeginForm())
          {
                    @Html.TextBox("title", "", new { placeholder = "Note Title" })
                    <div id="note">
                        @Html.TextArea("content", new { @placeholder = "Note Content" })
                        <br />
                        <label for="tags">Tags:</label>
                        @Html.TextArea("tags")
                    </div>
                    <p>Last Edited: Now</p>
                    <input type="submit" value="Create" />
          }
</div>

project-tiki/project-tiki/Views/NoteViewEdit/Index.cshtml
@model project_tiki.Models.NoteViewEditViewModel
@Styles.Render("~/public/css/editnote.css")

    @{
        ViewBag.Title = Model.TheNote.Title;

        ViewBag.Members = "";

        foreach (var m in Model.Members)
        {
            ViewBag.Members += m.UserName + " ";
        }
        
        ViewBag.TagString = "";

        foreach(var t in Model.TheNote.Tags)
        {
            ViewBag.TagString += t.Title + ", ";
        }
        String testTagString = ViewBag.TagString;
    }

<div class="row">
        @using (Html.BeginForm("Edited", "NoteViewEdit"))
        {
            @Html.TextBox("title", Model.TheNote.Title, new { maxlength=20, placeholder="Note Title" })
            <div>Current Members: @ViewBag.Members</div>

            <div id="note">
                @Html.TextArea("content", Model.TheNote.Content, new { placeholder="Write your note here" })
                <br />
                <label for="tags">Tags:</label>
                @Html.TextArea("tags", @testTagString, new { placeholder="Place your tags here, separated by commas" })
            </div>
            <p>Last Edited: @Model.TheNote.LastEdited</p>
            <input type="submit" value="Save" />
            <div style="display: none; visibility: hidden;">
                @Html.TextBox("noteid", Model.TheNote.NoteID)
                @Html.TextBox("bgColor", Model.TheNote.Background)
                @Html.TextBox("color", Model.TheNote.Color)
                @Html.TextBox("font", Model.TheNote.FontSource)
                @Html.TextBox("members", Model.Members)
            </div>
        }

    @Html.ActionLink("Edit Members", "ChangeMembers", new { noteid = Model.TheNote.NoteID }) |
    @Html.ActionLink("Edit Theme", "OpenEditTheme", new { id = Model.TheNote.NoteID })

</div>

project-tiki/project-tiki/Views/NoteViewEdit/OpenEditMembers.cshtml
@model project_tiki.Models.ViewNote
@Styles.Render("~/public/css/editnote.css")
@Styles.Render("~/public/css/editmembers.css")

       <h2>Edit Members</h2>
       
                <h3>Current Members</h3>
                @foreach (var member in ViewBag.Members)
                {
                    <div class="memberButtons">
                        <label>@member.UserName</label>
                        <button type="button" class="btn btn-danger">
                            <span class="glyphicon glyphicon-remove"></span>
                        </button>
                        </div>
                }
           
               <h3>Add a Member</h3>
                <p>Enter the username of the member you would like to add to this note</p>
                @using (Html.BeginForm("UserSearched", "NoteViewEdit"))
                {
                    @Html.TextBox("username")
                    <input type="submit" value="Search" />
                }

project-tiki/project-tiki/Views/NoteViewEdit/OpenEditTheme.cshtml
@model project_tiki.Models.ViewNote
@Styles.Render("~/public/css/editnote.css")
@Styles.Render("~/public/css/edittheme.css")

             <h2 class="modal-title">Edit Theme</h2>
            @using (Html.BeginForm("ChangeTheme", "NoteViewEdit"))
            {
                <h4>Note Color</h4>
                <div class="colors btn-group" data-toggle="buttons">
                    <label id="one" onclick="newColor(this.id)" style="background-color: #FFFFFF;" class="colors btn btn-default">
                        <input type="radio" />
                    </label> 
                    <label id="two" onclick="newColor(this.id)" style="background-color: #DDF9D9;" class="colors btn btn-default">
                        <input id="ctwo" type="radio" />
                    </label>
                    <label id="three" onclick="newColor(this.id)" style="background-color: #529A86;" class="colors btn btn-default">
                        <input id="cthree" type="radio" />
                    </label>
                    <label id="four" style="background-color: #D1FAFF;" class="colors btn btn-default" onclick="newColor(this.id)">
                        <input id="cfour" type="radio" />
                    </label>
                    </div>

                <h4>Note Font</h4>
                <div class="btn-group" data-toggle="buttons">
                    <label class="btn btn-default">
                        <input  id="fone" onclick="newFont(this.id)" type="radio" /> Arial
                    </label>
                    <label class="btn btn-default">
                        <input id="ftwo" onclick="newFont(this.id)" type="radio" /> Montserrat
                    </label>
                    <label class="btn btn-default">
                        <input id="fthree" onclick="newFont(this.id)" type="radio" /> Times
                    </label>
                    <label class="btn btn-default">
                        <input id="ffour" onclick="newFont(this.id)" type="radio"/> Roboto
                    </label>
                </div>

                <h4>Note Font Color</h4>
                <div class="btn-group" data-toggle="buttons">
                    <label id="fcone" onclick="newFontColor(this.id)" class="btn btn-default">
                        <input type="radio" /> White
                    </label>
                    <label id="fctwo" onclick="newFontColor(this.id)" style="color: #000000;" class="btn btn-default">
                        <input type="radio" /> Black
                    </label>
                    <label id="fcthree" onclick="newFontColor(this.id)" style="color: #E8432B;" class="btn btn-default">
                        <input type="radio" /> Red
                    </label>
                    <label id="fcfour" onclick="newFontColor(this.id)" style="color: #ACEBAE;" class="btn btn-default">
                        <input type="radio"/> Mint
                    </label>
                </div>
                <br />
                <br />

                <div style="display:none;">
                    @Html.TextBox("noteid", Model.NoteID)
                    @Html.TextBox("bgColor")
                    @Html.TextBox("color")
                    @Html.TextBox("font")

                </div>

                <script>

                        function newColor (idmaybe) {
                            var thing = document.getElementById(idmaybe);
                            var bg = document.getElementsByName("bgColor");
                            bg[0].value = thing.style.backgroundColor.toString();
                            bg[0].innerHTML = thing.style.backgroundColor.toString();

                            console.log(bg);
                        }

                        function newFontColor(idthing) {
                            var fthing = document.getElementById(idthing);
                            var fcolor = document.getElementsByName("color");
                            fcolor[0].value = fthing.style.backgroundColor.toString();
                        }

                        //function newFont(aidmaybe) {
                        //    var fthing = document.getElementById(aidmaybe);
                        //    var f = document.getElementsByName("font");
                        //    f[0].value = fthing.style.backgroundColor.toString();
                        //}
                </script>
                        <input type="submit" value="Save Changes" />
            }
   

project-tiki/project-tiki/Views/NoteViewEdit/RedirectPls.cshtml
﻿@model project_tiki.Models.NoteViewEditViewModel
@Styles.Render("~/public/css/editnote.css")
@Styles.Render("~/public/css/cproject.css")

<div class="text-center">
    <h1>@ViewBag.Message</h1>
</div>